# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logsumexp <- function(x) {
    .Call('_MAJAR_logsumexp', PACKAGE = 'MAJAR', x)
}

llbR0_j <- function(betajk_j_G, betajk_j_GT, sjk2_j_G, sjk2_j_GT, lambda, alpha) {
    .Call('_MAJAR_llbR0_j', PACKAGE = 'MAJAR', betajk_j_G, betajk_j_GT, sjk2_j_G, sjk2_j_GT, lambda, alpha)
}

deltis <- function(betajk_j_G, betajk_j_GT, sjk2_j_G, sjk2_j_GT, lambda, alpha) {
    .Call('_MAJAR_deltis', PACKAGE = 'MAJAR', betajk_j_G, betajk_j_GT, sjk2_j_G, sjk2_j_GT, lambda, alpha)
}

ll_R1_j <- function(bs2_j_G, bs2_j_GT, os22_j_G, os22_j_GT, b2s2_j_G, b2s2_j_GT, lambda, alpha, rho, tau2, sjk2_j_G, sjk2_j_GT) {
    .Call('_MAJAR_ll_R1_j', PACKAGE = 'MAJAR', bs2_j_G, bs2_j_GT, os22_j_G, os22_j_GT, b2s2_j_G, b2s2_j_GT, lambda, alpha, rho, tau2, sjk2_j_G, sjk2_j_GT)
}

rcpparma_hello_world <- function() {
    .Call('_MAJAR_rcpparma_hello_world', PACKAGE = 'MAJAR')
}

rcpparma_outerproduct <- function(x) {
    .Call('_MAJAR_rcpparma_outerproduct', PACKAGE = 'MAJAR', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_MAJAR_rcpparma_innerproduct', PACKAGE = 'MAJAR', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_MAJAR_rcpparma_bothproducts', PACKAGE = 'MAJAR', x)
}

